apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tinylink-ingress
  namespace: tinylink
  labels:
    app: tinylink
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: tinylink.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tinylink-service
                port:
                  number: 80
