apiVersion: v1
kind: Service
metadata:
  name: tinylink-service
  namespace: tinylink
  labels:
    app: tinylink
spec:
  type: ClusterIP
  selector:
    app: tinylink
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
